version: '3'

services:
  app:
    build:
      context: ./docker/app/
    working_dir: /var/www
    volumes:
      - ./:/var/www
  nginx:
    build:
      context: ./docker/nginx/
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8080:80
  database:
    image: mysql:5.7
    volumes:
      - sesh5db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=sesh5"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 3306:3306

volumes:
  sesh5db: