name: PHPStan
on: [push]
jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
#    container:
#      image: adamculp/php-code-quality:latest
#      volumes:
#        - ./:/app
    steps:
      - name: Analyse
        run: |
          pwd
          ls -l
