name: PHPStan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  analyse:
    needs: build
    name: Analyse
    runs-on: ubuntu-latest
#    container:
#      image: adamculp/php-code-quality:latest
#      volumes:
#        - ./:/app
    steps:
      - name: Analyse
        run: |
          pwd
          ls -l
